### ISSUE TITLE
Can you make a similar script for pulling OTA updates ?

### ISSUE THREAD

**Issue by Ammar64** [turistu/rmx3474-rooting#22]
I have realme 11 4G RMX3636.
I got an android 14 RUI 5 update but I'm afraid that if I installed it I might not be able to find the firmware on the internet for rooting or backup purposes.
So is there a way to download the firmware from realme servers to the laptop using a script like this ?

**Comment by amigaser** [comment]
https://github.com/R0rt1z2/realme-ota

**Comment by Ammar64** [comment]
> https://github.com/R0rt1z2/realme-ota

Thanks
