### ISSUE TITLE
What all variables to change if I want to change model ??

### ISSUE THREAD

**Issue by tarun-ainampudi** [turistu/rmx3474-rooting#23]
Since deep Realme 9 SE is not working I want to chage the model in this oppo k9s . how to get those values via adb commands. Thank You

**Comment by d4k6h** [comment]
why did you closed lol

**Comment by tarun-ainampudi** [comment]
check the codes you can easily understand what to change

**Comment by d4k6h** [comment]
@tarun-ainampudi does it worked for you?

**Comment by d4k6h** [comment]
https://github.com/turistu/rmx3474-rooting/issues/26

can you resolve it me for too please?
@tarun-ainampudi

**Comment by tarun-ainampudi** [comment]
currently it is not working, since deep testing servers are down.

**Comment by d4k6h** [comment]
> currently it is not working, since deep testing servers are down.
> 
when did the servers last active
have you any idea of that lol?

**Comment by tarun-ainampudi** [comment]
Till 2023 May I guess

**Comment by d4k6h** [comment]
> Till 2023 May I guess
do you have any telegram or something? so i can clear my queries there w you?

**Comment by tarun-ainampudi** [comment]
Yeah @tarun_xy
